import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
//import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:aid_able/pages/auth_page.dart';
import 'package:flutter/material.dart';
//import '../login/login.dart';
//import 'package:image_picker/image_picker.dart';
import 'dart:io';