name: aid_able
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^8.1.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: 4.14.0
  google_sign_in: ^6.2.1
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  awesome_notifications: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - assets/
    - assets/food.jpg
    - assets/clothes.jpeg
    - assets/books.jpg
    - assets/Blanket.png
    - assets/stationary.jpg
