// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMf9_TfDj9tYTGclxwjPd70U0dlwaTYc',
    appId: '1:44688773069:web:a383638b61e0ec45653e84',
    messagingSenderId: '44688773069',
    projectId: 'aidable',
    authDomain: 'aidable.firebaseapp.com',
    storageBucket: 'aidable.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9Lcx4SVCcfAY6mtfqP1gmM8gM_ODZ4Y',
    appId: '1:44688773069:android:d63a757c6d68ad5d653e84',
    messagingSenderId: '44688773069',
    projectId: 'aidable',
    storageBucket: 'aidable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGRMlOHR1gzz-VtOjG6lbdQ73UBAoHWk',
    appId: '1:44688773069:ios:4df2ff5b37020192653e84',
    messagingSenderId: '44688773069',
    projectId: 'aidable',
    storageBucket: 'aidable.appspot.com',
    iosBundleId: 'com.example.aidAble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGRMlOHR1gzz-VtOjG6lbdQ73UBAoHWk',
    appId: '1:44688773069:ios:f574025e02e6ee92653e84',
    messagingSenderId: '44688773069',
    projectId: 'aidable',
    storageBucket: 'aidable.appspot.com',
    iosBundleId: 'com.example.aidAble.RunnerTests',
  );
}
